spring:
  datasource:
    username: root
    password: Mysql2019
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # formatSQL得这样写
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: warn
    com.blog.example.demo: info
  file: log/blog-pro.log

server:
  port: 8081